name: kanban

description: "Inventory Management Dashboard"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route: ^10.0.1
  flutter_svg: ^2.0.10+1
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  riverpod_generator: ^2.6.5
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/config/gen/
  assets:
    outputs:
      class_name: AppAssets
      directory_path_enabled: true

  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: false

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter-Bold.otf
          weight: 700
